// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX0TlO6mdeZEu7p5cz9MdmKJAk6UEjuvg',
    appId: '1:539254845226:web:9c01af5ed1d8665b45f853',
    messagingSenderId: '539254845226',
    projectId: 'spimo-project',
    authDomain: 'spimo-project.firebaseapp.com',
    storageBucket: 'spimo-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn0akHgKvAaXkU8WJzuEnHXuiayffuUDk',
    appId: '1:539254845226:android:d5dd6095324e22f645f853',
    messagingSenderId: '539254845226',
    projectId: 'spimo-project',
    storageBucket: 'spimo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoBIgJbzC-FM5hGIWzHboh3OQpnY6-KsQ',
    appId: '1:539254845226:ios:eda592793e4048af45f853',
    messagingSenderId: '539254845226',
    projectId: 'spimo-project',
    storageBucket: 'spimo-project.appspot.com',
    iosClientId: '539254845226-b761469v3mn2sd29glubc1jt5pl56atk.apps.googleusercontent.com',
    iosBundleId: 'com.example.spimo',
  );
}
